version: "3"
services:
  react-app:
    image: react-app
    container_name: client
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app
    volumes:
      - ./client:/usr/src/app
  api-server:
    image: api-server
    container_name: server
    ports:
      - "9000:9000"
    networks:
      - mern-app
    depends_on:
      - mongo
    volumes:
      - ./server:/usr/src/app
  mongo:
    image: mongo:3.6.19-xenial
    container_name: mongo
    ports:
      - "27018:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
